### PR TITLE
Custom URL triggers + Proxy per Custom URL (Chrome)

### PR DESCRIPTION
**Pull request by neptuwunium**
These commits add the ability to add custom URLs to proxy, with optionally the ability to add a custom proxy to that specific URL.

It has some minor optimizations too, along with that an automatic debug switch which automatically enables debugging if the extension is unpacked.

Note: These commits only affects the chrome version.

### CODE REVIEW

**Comment by dvcrn** [comment]
Wow, someone actually took the time to fiddle around my messy code. 
Cool pull request, but keep in mind that the main servers used by ProxMate are using a whitelist filter to avoid a use-it-for-everything behaviour

**Comment by neptuwunium** [comment]
Aha, undersood.
Added a patch which enforces either/and the unique custom proxy and the general custom proxy.

**Comment by dvcrn** [comment]
Would love to have the all-behaviour but traffic costs money and this might easily get highly illegal. Checking the pull request asap!

**Comment by dvcrn** [comment]
Released in newest ProxMate (2.4.1)
Had to remove the management dependency though as it was prompting the user for new permissions

**Pull request merged**
